#ifndef APPBOX_WIDGETS_COMMON_HPP
#define APPBOX_WIDGETS_COMMON_HPP

#include <wx/wx.h>

enum AppboxID
{
    APPBOX_LOWEST = wxID_HIGHEST + 1,
    APPBOX_PACKER_MAINFRAME_PROCESS_BUTTON,
    APPBOX_PACKER_MAINFRAME_STARTUP_FILES_BUTTON,
};

#endif
