# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: ci-win

on: [push]

permissions:
  contents: read

env:
  WX_INSTALL_DIR: ${{github.workspace}}/.deps/wxWidgets

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - name: Build
        env:
          CMAKE_PREFIX_PATH: ${{env.WX_INSTALL_DIR}}
        run: cmake --workflow --preset ${{matrix.build_type}}

      - name: Upload build artifact if failed
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: fail_artifact_${{matrix.build_type}}
          path: ./build/*

      - name: Upload release artifacts
        uses: actions/upload-artifact@v7
        with:
          path: ./build/Release/appbox-*.zip
          archive: false
